### PR TITLE
Adopting Design from grin.ninja

### PR DESCRIPTION
**Pull request by i1skn**
This PR implements a design from grin.ninja - https://hq.grin.ninja/ as a Jekyll theme.
Caveats:
* Not a whole lot is now can be configurable from `*.yml` files. I decided that we can go incrementally on this.
* On pages, like `learn` and `funding` "Home" link would appear and would lead to `/`. It means that it would work on `example.com`, but not on `example.com/super-site/`. Not sure how to fix it for now.

The preview of the website is here: https://i1skn.github.io/site-test/. 
Although, only differences from the https://hq.grin.ninja/ are:
* https://i1skn.github.io/site-test/learn
* https://i1skn.github.io/site-test/funding

### CODE REVIEW

**Comment by ignopeverell** [comment]
@i1skn this is great! I agree on making this a little more incremental. Would you prefer leaving this PR open for these improvements and potential @jollygrin design improvements as well or do you prefer progressing with additional PRs?

**Comment by i1skn** [comment]
I think it's better to proceed with additional PRs:
* People would see the text they editing right on the new design.
* Bugs/missing features would be found faster because more users would see/play with it.

@ignopeverell @JollyGrin What do you think?

**Comment by ignopeverell** [comment]
Merged!

**Comment by JollyGrin** [comment]
Sounds good to me! I'll continue making any design improvements on hq.grin.ninja for simplicity sake, but as you said could me added with additional pull requests :)

**Pull request merged**
